---
name: ci
on: push

jobs:
  build-docker:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/bake-action@v3
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          TAG: ${{ github.ref_name }}
        with:
          push: true
          files: 'docker-bake.json'
      - uses: docker/bake-action@v3
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          push: true
          files: 'docker-bake.json'
